### ISSUE TITLE
Cannot connect AWS API anymore

### ISSUE THREAD

**Issue by JohanHardy** [bachya/aioambient#254]
https://github.com/bachya/aioambient/blob/b22a1a20e4eea730e11ea3d78537503a9432123f/aioambient/websocket.py#L18

I'm seeing an issue to connect AmbientWeather. [rt2.ambientweather.net](http://rt2.ambientweather.net/) won't allow WebSocket connections (which is the hostname aioambient uses), however [rt.ambientweather.net](http://rt.ambientweather.net/) seems to connect fine.

I changed line 18 in /usr/local/lib/python3.11/site-packages/aioambient/websocket.py from:

WEBSOCKET_API_BASE = "https://rt2.ambientweather.net/"

to

WEBSOCKET_API_BASE = "https://rt.ambientweather.net/"

And restarted HA and all seems to be fine again. For now... :)

**Comment by bachya** [comment]
I assume you're coming from https://github.com/home-assistant/core/issues/94205—as I mentioned, there is an issue with the Ambient Weather API.

Their official docs list https://rt2.ambientweather.net as the websocket endpoint. They've changed this in the past without warning, so I'd like to see some official indication from them before I update this library.

**Comment by JohanHardy** [comment]
I appreciate your response. 
My perspective is that it might be intriguing to assemble a collection of WebSocket endpoints, which could essentially create a redundancy. Thus, whenever the library attempts to reconnect, it would prevent the service from experiencing any delays or stagnation as we have seen in this week. The intex 0 would be the rt2 endpoints and the index 1 rt ; as per specification.
