### ISSUE TITLE
On_disconnect is cancelling the watchdog

### ISSUE THREAD

**Issue by fancygaphtrn** [bachya/aioambient#56]
**Describe the bug**
As part of the issue with ambient in Home assistant.  
https://github.com/home-assistant/core/issues/32956

When the websocket is closed for whatever reason, the on_disconnect routine is cancelling the watchdog.

I will attempt to get home assistant logs, but my ambient is continually stopping with the watchdog never expiring in the home assistant logs.   I believe the websocket is being closed by the ambient server and then the watchdog gets cancelled.

**Expected behavior**
For whatever the reason the websocket is closed it would think the watchdog would remain and cause the websocket to reopen.

**Additional context**

I will be glad to support any way you say.

**Comment by bachya** [comment]
Ah, thank you for this heads up. You're right: I'm killing the watchdog through _any_ disconnection, when really, I should only kill it when an `aioambient` user requests a disconnect. I'll work on a patch.
