### ISSUE TITLE
Leak sensors do not change state

### ISSUE THREAD

**Issue by mremedi2023** [bachya/aioambient#591]
Hello, I have 4 leak sensors installed, they report correctly to the WS-5000 control panel but the status never changes in Home Assistant.

<img width="720" alt="Screenshot_4" src="https://github.com/user-attachments/assets/c7999295-b8a8-43ab-972e-6d32290c4a7e">

**Comment by mremedi2023** [comment]
They are always in the same state (dry) regardless of whether they detect humidity or wetness.

<img width="196" alt="Screenshot_5" src="https://github.com/user-attachments/assets/173ee52f-52f6-4679-8248-7e119fd6d422">

**Comment by bachya** [comment]
You're reporting an issue regarding the Home Assistant integration; please file an issue with that project: https://github.com/home-assistant/core
