### ISSUE TITLE
Reconnect on disconnect

### ISSUE THREAD

**Issue by simplextech** [bachya/aioambient#7]
Problem:  AmbientWeather Socket.IO disconnects periodically

Is there a built in reconnect option available that I'm not seeing?  If so please give direction to the blind.  If not this would be a very nice feature.

**Comment by bachya** [comment]
This already exists (and was implemented in https://github.com/bachya/aioambient/pull/4) – reconnects happen automatically and by default. Are you seeing situations where that doesn't occur?

**Comment by simplextech** [comment]
I was having an issue with reconnect.  It was retrying but not connecting.  I think it was my issue though.  So I think this is closed.
