### ISSUE TITLE
Make 5 day forecast available

### ISSUE THREAD

**Issue by Tokynet** [bachya/aioambient#70]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When looking at the AmbientWeather dashboard, you can see it offers a 5 day forecast (and many other historical details), I would like to be able to pull that 5 day forecast and make it available.

**Additional context**
N/A

**Comment by bachya** [comment]
Where in the Ambient Weather API would this data come from?

**Comment by Tokynet** [comment]
I do not know, but the data is visible the ambientweather dashboard:
![dashboard-forecast](https://user-images.githubusercontent.com/274691/89723676-756cb800-d9c7-11ea-85ce-32691d71218e.png)

**Comment by bachya** [comment]
I just looked at [the API docs](https://ambientweather.docs.apiary.io/) and don't see anything related to weather forecast.
