### ISSUE TITLE
Release needed to resolve websockets conflict

### ISSUE THREAD

**Issue by timmo001** [bachya/aioambient#87]
**Describe the solution you'd like**
A release is needed to help resolve a conflict in the HA Core dependencies with a new feature PR. See:

https://github.com/home-assistant/core/pull/53443/#issuecomment-886183899

**Additional context**

https://github.com/bachya/aioambient/blob/7be34c7adff6d3a7a4e6746fd701ff3e45cb7e91/pyproject.toml#L64

https://github.com/bachya/aioambient/compare/1.2.4...HEAD

4bcac4e

**Comment by bachya** [comment]
To confirm, do you need a release of the library as is? Or do you need the `websockets` library pinned to some new version?￼

**Comment by timmo001** [comment]
As is. The pinned version is fine as it is

**Comment by bachya** [comment]
1.2.5 released: https://github.com/bachya/aioambient/releases/tag/1.2.5
