### ISSUE TITLE
Example usage from documentation leads to an unhandled exception

### ISSUE THREAD

**Issue by zx5000** [bachya/aioambient#90]
**Describe the bug**
This error message where xxxxxxx are real values from my api key and app key.

```
  File "aioamient.py", line 13, in main
    client = Client("xxxxxxxx", "xxxxxxx", session)
TypeError: __init__() takes 3 positional arguments but 4 were given

```
**To Reproduce**
run the command
`./aioamient.py 
`  or
`python3 aioamient.py
`
**Expected behavior**
Should produce output

**Screenshots**
```
pi@rasp-web:~/fetchapp $ ./aioamient.py 
Traceback (most recent call last):
  File "./aioamient.py", line 27, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./aioamient.py", line 13, in main
    client = Client("real_api_key", "real_app_key", session)
TypeError: __init__() takes 3 positional arguments but 4 were given

```

**Comment by bachya** [comment]
`aioamient.py` is not a file provided by this repository; I assume it's a script you've created? Nevertheless, I'm assuming that an incorrectly documented example led to this; I'll get that fixed. Thanks!
